# Generated by Django 4.1.5 on 2023-02-20 07:35

import autoslug.fields
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_news_alt_alter_news_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageGenerator',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', primary_key=True, serialize=False)),
                ('excerpt', models.TextField(max_length=155)),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('meta_description', models.TextField(max_length=155)),
                ('meta_keywords', models.TextField(max_length=155)),
                ('status', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='page/')),
                ('alt', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='alt',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
